name: webview_flutter_web_example
description: Demonstrates how to use the webview_flutter_web plugin.
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.1  # データ保存用
  hive_flutter: ^1.1.0  # FlutterでのHive使用
  mobile_scanner: ^2.0.0  # QRコード読み取り用


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
